import {
  AppWindow,
  AtSignIcon,
  Bot,
  ChartAreaIcon,
  ChartNoAxesColumn,
  CoffeeIcon,
  Computer,
  Contact,
  Gamepad,
  HomeIcon,
  Layers,
  Library,
  Rss,
} from 'lucide-react';
import { MenuItem } from '@/types/menu';

export const MENU_ITEMS: Array<MenuItem> = [
  {
    title: 'Home',
    url: '/',
    icon: HomeIcon,
    isActive: true,
    changeFrequency: 'daily',
    priority: 1,
  },
  {
    title: 'Data',
    url: '#',
    icon: ChartAreaIcon,
    isActive: true,
    changeFrequency: 'daily',
    priority: 0.9,
    items: [
      {
        title: 'Stats',
        url: '/stats',
        icon: ChartNoAxesColumn,
        isActive: true,
        changeFrequency: 'daily',
        priority: 0.8,
      },
      {
        title: 'Posts',
        url: '/blog',
        icon: Rss,
        isActive: true,
        changeFrequency: 'daily',
        priority: 0.8,
      },
      {
        title: 'Projects',
        url: '/projects',
        icon: CoffeeIcon,
        isActive: true,
        changeFrequency: 'daily',
        priority: 0.7,
      },
    ],
  },

  {
    title: 'About',
    url: '#',
    icon: Library,
    isActive: true,
    changeFrequency: 'weekly',
    priority: 0.2,
    items: [
      {
        title: 'Me',
        url: '/about',
        icon: Contact,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.2,
      },
      {
        title: 'Contact',
        url: '/contact',
        icon: AtSignIcon,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.2,
      },
      {
        title: 'Uses',
        url: '/uses',
        icon: Computer,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.3,
      },
      {
        title: 'Colophon',
        url: '/colophon',
        icon: Layers,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.4,
      },
    ],
  },

  {
    title: 'Apps',
    icon: AppWindow,
    url: '#',
    isActive: true,
    changeFrequency: 'weekly',
    priority: 0.2,
    items: [
      {
        title: 'AI',
        url: '/apps/ai',
        icon: Bot,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.2,
      },
      {
        title: 'BrowserQuest',
        url: '/apps/browser-quest',
        icon: Gamepad,
        isActive: true,
        changeFrequency: 'weekly',
        priority: 0.2,
      },
    ],
  },
];
